const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
    getCategories: () => ipcRenderer.invoke('db-get-categories'),
    getItems: () => ipcRenderer.invoke('db-get-items'),
    submitOrder: (cart, orderType, customerId, paymentMethod, discount) => ipcRenderer.invoke('db-submit-order', cart, orderType, customerId, paymentMethod, discount),
    getCustomer: (phone) => ipcRenderer.invoke('db-get-customer', phone),
    getAllCustomers: () => ipcRenderer.invoke('db-get-all-customers'),
    getCustomerOrders: (customerId) => ipcRenderer.invoke('db-get-customer-orders', customerId),
    getPendingOrders: () => ipcRenderer.invoke('db-get-pending-orders'),
    getTodayOrders: () => ipcRenderer.invoke('db-get-today-orders'),
    markOrderReady: (orderId) => ipcRenderer.invoke('db-mark-order-ready', orderId),
    refundOrder: (orderId) => ipcRenderer.invoke('db-refund-order', orderId),
    saveCustomer: (customer) => ipcRenderer.invoke('db-save-customer', customer),
    getDashboardStats: (startDate, endDate) => ipcRenderer.invoke('db-get-dashboard-stats', startDate, endDate),
    getInventory: () => ipcRenderer.invoke('db-get-inventory'),
    addInventoryItem: (name, unit, stock, thresh) => ipcRenderer.invoke('db-add-inventory', name, unit, stock, thresh),
    addMenuItem: (catId, name, price, img) => ipcRenderer.invoke('db-add-menu-item', catId, name, price, img),
    addRecipe: (itemId, invId, qty) => ipcRenderer.invoke('db-add-recipe', itemId, invId, qty),
    deleteInventoryItem: (id) => ipcRenderer.invoke('db-delete-inventory', id),
    deleteMenuItem: (id) => ipcRenderer.invoke('db-delete-menu-item', id),
    updateInventoryItem: (id, name, unit, stock, thresh) => ipcRenderer.invoke('db-update-inventory', id, name, unit, stock, thresh),
    updateMenuItem: (id, catId, name, price, img) => ipcRenderer.invoke('db-update-menu-item', id, catId, name, price, img),
    getSettings: () => ipcRenderer.invoke('db-get-settings'),
    saveSettings: (storeName, taxNumber) => ipcRenderer.invoke('db-save-settings', storeName, taxNumber),
    loginUser: (pin) => ipcRenderer.invoke('db-login-user', pin),
    getUsers: () => ipcRenderer.invoke('db-get-users'),
    addUser: (name, pin, role) => ipcRenderer.invoke('db-add-user', name, pin, role),
    deleteUser: (id) => ipcRenderer.invoke('db-delete-user', id),
    openShift: (name, cash) => ipcRenderer.invoke('db-open-shift', name, cash),
    getCurrentShift: () => ipcRenderer.invoke('db-get-shift'),
    closeShift: (actualCash, shiftId) => ipcRenderer.invoke('db-close-shift', actualCash, shiftId),
    getZReport: (shiftId) => ipcRenderer.invoke('db-get-z-report', shiftId),
    checkLicense: () => ipcRenderer.invoke('check-license'),
    activateLicense: (key) => ipcRenderer.invoke('activate-license', key)
});
